services:
  product-service:
    environment:
      NODE_ENV: development
    volumes:
      - ./product-service/src:/app/src
      - ./product-service/prisma:/app/prisma
    command: node src/index.js

  order-service:
    environment:
      NODE_ENV: development
    volumes:
      - ./order-service/src:/app/src
    command: node src/index.js

  auth-service:
    environment:
      NODE_ENV: development
    volumes:
      - ./auth-service/src:/app/src
      - ./auth-service/prisma:/app/prisma
    command: node src/index.js

  api-gateway:
    environment:
      NODE_ENV: development
    volumes:
      - ./api-gateway/src:/app/src
    command: node src/index.js

